resource_group_name = "mhhd.fauzan016"
app_name           = "portal-admin"
environment        = "dev"
location           = "southeastasia"
sku_name           = "F1"
docker_username    = "<username>"
docker_password    = "<token>"